chore: Restored central dispatch script at publish.yml, removed filtering from node for testing
Signed-off-by: mrickard <maurice@mauricerickard.com>

diff --git a/.github/workflows/publish-node.yml b/.github/workflows/publish-node.yml
--- a/.github/workflows/publish-node.yml
+++ b/.github/workflows/publish-node.yml
@@ -1,14 +1,13 @@
 name: Publish Node Layers
 
 on:
-  push:
-    tags: [master]
+  workflow_call:
   workflow_dispatch:
-    inputs:
-      tag:
-        description: 'Enter a tagged release to publish.'
-        required: true
-        type: string
+#    inputs:
+#      tag:
+#        description: 'Enter a tagged release to publish.'
+#        required: true
+#        type: string
 
 env:
   release_tag: ''
@@ -21,35 +20,35 @@ jobs:
         node-version: [16, 18, 20]
     steps:
       - uses: actions/checkout@v4
-      - name: Set tag env var
-        id: release_tag
-        run: |
-          if [[ ! -z ${{ github.event.inputs.tag }} ]]; then 
-            echo "release_tag=${{ github.event.inputs.tag }}_nodejs" >> "$GITHUB_ENV"
-            echo "Publishing from workflow_dispatch ${{ github.event.inputs.tag }}_nodejs"
-          else
-            echo "Publishing from GitHub event"
-            echo "release_tag=${{ github.event.ref }}" >> "$GITHUB_ENV"
-            echo "Publishing from GitHub event: new tag ${{ github.event.ref }}"
-          fi
-        shell: bash
+#      - name: Set tag env var
+#        id: release_tag
+#        run: |
+#          if [[ ! -z ${{ github.event.inputs.runtime }} ]]; then
+#            echo "release_tag=${{ github.event.inputs.tag }}_nodejs" >> "$GITHUB_ENV"
+#            echo "Publishing from workflow_dispatch ${{ github.event.inputs.tag }}_nodejs"
+#          else
+#            echo "Publishing from GitHub event"
+#            echo "release_tag=${{ github.event.ref }}" >> "$GITHUB_ENV"
+#            echo "Publishing from GitHub event: new tag ${{ github.event.ref }}"
+#          fi
+#        shell: bash
       - name: Use Node.js ${{ matrix.node-version }}.x
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Check Tag
-        id: node-check-tag
-        run: |
-          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_nodejs/$ ]]; then
-              echo "match=true" >> $GITHUB_OUTPUT
-          elif [[ ${{ env.release_tag }} =~ ^v[0-9]+(\.[0-9]+)*_nodejs$ ]]; then
-              echo "match=true" >> $GITHUB_OUTPUT
-          else 
-              echo "::error::Invalid tag"
-              exit 1
-          fi
+#      - name: Check Tag
+#        id: node-check-tag
+#        run: |
+#          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_nodejs/$ ]]; then
+#              echo "match=true" >> $GITHUB_OUTPUT
+#          elif [[ ${{ env.release_tag }} =~ ^v[0-9]+(\.[0-9]+)*_nodejs$ ]]; then
+#              echo "match=true" >> $GITHUB_OUTPUT
+#          else
+#              echo "::error::Invalid tag"
+#              exit 1
+#          fi
       - name: Run Node ${{ matrix.node-version }} unit tests
-        if: steps.node-check-tag.outputs.match == 'true'
+#        if: steps.node-check-tag.outputs.match == 'true'
         run: cd nodejs && npm ci && npm run test
       - name: Publish layer
         run: make publish-nodejs${{ matrix.node-version }}x-ci
